#!/usr/bin/env bash

set -e

# echo "dockerizing ["$@"]"

# https://stackoverflow.com/questions/58677021/prevent-git-bash-automatically-change-the-path
MSYS_NO_PATHCONV=1 docker compose run --rm trivial-docker-example "$@"